#! /bin/bash

## dir,path
__FILE__=$_
BASE_DIR_PATH=${__FILE__%/./*}
WORKING_DIR_PATH=$PWD

# src dir,path
SRC_DIR_PATH=~/src
LOCAL_DIR_PATH=~/local
ZSH_SRC_DIR_PATH=$SRC_DIR_PATH/zsh
VIM_SRC_DIR_PATH=$SRC_DIR_PATH/vim
TMUX_SRC_DIR_PATH=$SRC_DIR_PATH/tmux
GIT_SRC_DIR_PATH=$SRC_DIR_PATH/git
LUAJIT_SRC_DIR_PATH=$SRC_DIR_PATH/luajit
CTAGS_SRC_DIR_PATH=$SRC_DIR_PATH/ctags
SILVER_SEARCHER_SRC_DIR_PATH=$SRC_DIR_PATH/silver_searcher
PECO_SRC_DIR_PATH=$SRC_DIR_PATH/peco
NEOVIM_SRC_DIR_PATH=$SRC_DIR_PATH/neovim  # 使用していない

# repositories
ZSH_REPOSITORY='git://github.com/zsh-users/zsh'
VIM_REPOSITORY='git://github.com/vim-jp/vim'
TMUX_REPOSITORY='git://git.code.sf.net/p/tmux/tmux-code'
GIT_REPOSITORY='git://github.com/gitster/git'
LUAJIT_REPOSITORY='http://luajit.org/git/luajit-2.0.git'
CTAGS_REPOSITORY='git://github.com/fishman/ctags'
SILVER_SEARCHER_REPOSITORY='git://github.com/ggreer/the_silver_searcher'
PECO_REPOSITORY='git://github.com/peco/peco'
NEOVIM_REPOSITORY='git://github.com/neovim/neovim'  # 使用していない

# base dir,path
CACHE_DIR=cache
CACHE_DIR_PATH=~/.$CACHE_DIR

## init
# source or local
[[ -d $SRC_DIR_PATH ]]                          || mkdir $SRC_DIR_PATH
[[ -d $LOCAL_DIR_PATH ]]                        || mkdir $LOCAL_DIR_PATH
[[ -d $ZSH_SRC_DIR_PATH ]]                      || git clone $ZSH_REPOSITORY $ZSH_SRC_DIR_PATH
[[ -d $VIM_SRC_DIR_PATH ]]                      || git clone $VIM_REPOSITORY $VIM_SRC_DIR_PATH
[[ -d $TMUX_SRC_DIR_PATH ]]                     || git clone $TMUX_REPOSITORY $TMUX_SRC_DIR_PATH
[[ -d $GIT_SRC_DIR_PATH ]]                      || git clone $GIT_REPOSITORY $GIT_SRC_DIR_PATH
[[ -d $LUAJIT_SRC_DIR_PATH ]]                   || git clone $LUAJIT_REPOSITORY $LUAJIT_SRC_DIR_PATH
[[ -d $CTAGS_SRC_DIR_PATH ]]                    || git clone $CTAGS_REPOSITORY $CTAGS_SRC_DIR_PATH
[[ -d $SILVER_SEARCHER_SRC_DIR_PATH ]]          || git clone $SILVER_SEARCHER_REPOSITORY $SILVER_SEARCHER_SRC_DIR_PATH
[[ -d $PECO_SRC_DIR_PATH ]]                     || git clone $PECO_REPOSITORY $PECO_SRC_DIR_PATH
[[ -d $NEOVIM_SRC_DIR_PATH ]]                   || git clone $NEOVIM_REPOSITORY $NEOVIM_SRC_DIR_PATH  # 使用していない
# cache dir
[[ -d $CACHE_DIR_PATH ]]                        || mkdir $CACHE_DIR_PATH
[[ -d $CACHE_DIR_PATH/yankring ]]               || mkdir $CACHE_DIR_PATH/yankring

## update source files
printf "### git pull zsh src.\n"
cd $ZSH_SRC_DIR_PATH && git pull
printf "### git pull vim src.\n"
cd $VIM_SRC_DIR_PATH && git pull
printf "### git pull tmux src.\n"
cd $TMUX_SRC_DIR_PATH && git pull
printf "### git pull git src.\n"
cd $GIT_SRC_DIR_PATH && git pull
printf "### git pull luajit src.\n"
cd $LUAJIT_SRC_DIR_PATH && git pull
printf "### git pull ctags src.\n"
cd $CTAGS_SRC_DIR_PATH && git pull
printf "### git pull silver_searcher src.\n"
cd $SILVER_SEARCHER_SRC_DIR_PATH && git pull
printf "### git pull peco src.\n"
cd $PECO_SRC_DIR_PATH && git pull
printf "### git pull neovim src.\n"
cd $NEOVIM_SRC_DIR_PATH && git pull  # 使用していない

### copy files
cd $BASE_DIR_PATH
# zsh
printf "### create symlink for zsh configs.\n"
ln -sf  $BASE_DIR_PATH/zshrc ~/.zshrc
ln -sfn $BASE_DIR_PATH/zsh.d ~/.zsh.d
# vim
printf "### create symlink for vim config.\n"
ln -sf  $BASE_DIR_PATH/vimrc ~/.vimrc
ln -sfn $BASE_DIR_PATH/vim   ~/.vim
# tmux
printf "### create symlink for tmux config.\n"
ln -sf $BASE_DIR_PATH/tmux.conf ~/.tmux.conf
# peco
printf "### create symlink for peco config.\n"
ln -sfn $BASE_DIR_PATH/peco ~/.peco
# pry
printf "### create symlink for pry config.\n"
ln -sf $BASE_DIR_PATH/pryrc ~/.pryrc

cd $WORKING_DIR_PATH
printf "### sync complete.\n"

# restart
exec zsh
