aliases:
  rebuild:
  - r
  restart:
  - re
substitute-path: []
show-location-expr: false
source-list-line-color: null
source-list-arrow-color: ""
source-list-keyword-color: ""
source-list-string-color: ""
source-list-number-color: ""
source-list-comment-color: ""
debug-info-directories:
- ~/.dlv/debug/.build-id
