#!/usr/bin/env bash

__FILE__=$_
BASE_DIR_PATH=$(cd $(dirname $__FILE__);pwd)
BASE_DIR_PATH=${BASE_DIR_PATH%/scripts*}

# OS info
OS_INFO=darwin

# Homebrew
HOMEBREW_INSTALL_DIR_PATH=/opt/homebrew

# local dir
LOCAL_DIR_PATH=~/local
LOCAL_BIN_DIR_PATH=$LOCAL_DIR_PATH/bin
LOCAL_LIB_DIR_PATH=$LOCAL_DIR_PATH/lib
LOCAL_JAR_DIR_PATH=$LOCAL_DIR_PATH/jar
LOCAL_INCLUDE_DIR_PATH=$LOCAL_DIR_PATH/include
SUBMODULES_DIR_PATH=$BASE_DIR_PATH/modules

# submodules src dir
ASDF_SRC_DIR_PATH=$SUBMODULES_DIR_PATH/asdf
CTAGS_SRC_DIR_PATH=$SUBMODULES_DIR_PATH/ctags
GIT_SRC_DIR_PATH=$SUBMODULES_DIR_PATH/git
GH_CLI_SRC_DIR_PATH=$SUBMODULES_DIR_PATH/gh-cli
JQ_SRC_DIR_PATH=$SUBMODULES_DIR_PATH/jq
THE_SILVER_SEARCHER_SRC_DIR_PATH=$SUBMODULES_DIR_PATH/the_silver_searcher
TMUX_CODE_SRC_DIR_PATH=$SUBMODULES_DIR_PATH/tmux
TMUX_MEM_CPU_LOAD_SRC_DIR_PATH=$SUBMODULES_DIR_PATH/tmux-mem-cpu-load
VIM_SRC_DIR_PATH=$SUBMODULES_DIR_PATH/vim
ZSH_SRC_DIR_PATH=$SUBMODULES_DIR_PATH/zsh

# docs
DOCS_DIR_PATH=$BASE_DIR_PATH/docs

# claude
CLAUDE_DIR_PATH=$BASE_DIR_PATH/claude

# git
GIT_DIR_PATH=$BASE_DIR_PATH/git

# config
CONFIG_DIR_PATH=~/.config

# cache
CACHE_DIR_PATH=~/.cache

# log
LOG_DIR_PATH=~/log
MYSQL_LOG_DIR_PATH=$LOG_DIR_PATH/mysql
MYSQL_GENERAL_LOG_FILE_PATH=$MYSQL_LOG_DIR_PATH/query.log
MYSQL_SLOW_QUERY_LOG_FILE_PATH=$MYSQL_LOG_DIR_PATH/slow_query.log

# works
WORKS_DIR_PATH=~/works
TMP_DIR_PATH=$WORKS_DIR_PATH/tmp
MEMOLIST_DIR_PATH=$WORKS_DIR_PATH/memolist
GIT_WORKTREES_DIR_PATH=$WORKS_DIR_PATH/git_worktrees
CURSOR_WORKSPACES_DIR_PATH=$WORKS_DIR_PATH/cursor_workspaces
DOCKER_DIR_PATH=$WORKS_DIR_PATH/docker
DOCKER_MYSQL_DIR_PATH=$DOCKER_DIR_PATH/mysql/

# memolist task markdown file
MEMOLIST_TASK_MARKDOWN_FILE_PATH=$MEMOLIST_DIR_PATH/00-task.md

# memolist prompt markdown file
MEMOLIST_TMP_PROMPT_FILE_PATH=$MEMOLIST_DIR_PATH/00-prompt.md

# memolist tmp file
MEMOLIST_TMP_MARKDOWN_FILE_PATH=$MEMOLIST_DIR_PATH/00-tmp.md
MEMOLIST_TMP_SQL_FILE_PATH=$MEMOLIST_DIR_PATH/00-tmp.sql
MEMOLIST_TMP_TEXT_FILE_PATH=$MEMOLIST_DIR_PATH/00-tmp.txt
MEMOLIST_TMP_UML_FILE_PATH=$MEMOLIST_DIR_PATH/00-tmp.uml
MEMOLIST_TMP_JSON_FILE_PATH=$MEMOLIST_DIR_PATH/00-tmp.json
MEMOLIST_TMP_RUBY_FILE_PATH=$MEMOLIST_DIR_PATH/00-tmp.rb
MEMOLIST_TMP_DIFF_FILE_PATH=$MEMOLIST_DIR_PATH/00-tmp.diff

# markdown_texts
MARKDOWN_TEXTS_DIR_PATH=~/markdown_texts
