# ログインと同時にtmuxアタッチ
if (( ! $#TMUX && ! $#STY )); then
  if type tmux >/dev/null 2>&1; then
    if tmux has-session; then
      tmux -u attach && print 'tmux attached session'
    else
      tmux -u new-session && print 'tmux created new session'
    fi
  fi
fi
